# -*- coding: utf-8 -*-
"""Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTph0NYjLhwdq6SZxOMQLP-5sMXTXFYg
"""

import requests
from dotenv import load_dotenv
import os
load_dotenv()
api_key = os.getenv('API_KEY')
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"

city = input("Enter city name(Capitalise first letter): ")
params = {"q": city, "appid": API_KEY, "units": "metric"}
response = requests.get(BASE_URL, params=params)
data = response.json()

if data.get("cod") != 200:
    print("City not found!")
else:
    weather = data["weather"][0]["description"].capitalize()
    temp = data["main"]["temp"]
    humidity = data["main"]["humidity"]
    wind_speed = data["wind"]["speed"]

    print(f"\nWeather: {weather}\nTemperature: {temp}°C\nHumidity: {humidity}%\nWind Speed: {wind_speed} m/s")